### ISSUE TITLE
Leap Year isn't always right

### ISSUE THREAD

**Issue by Joerg9** [SoftwareDojo/Katas#2]
Katas/C#/Katas/LeapYear/LeapYear.cs 

The solution does not match all conditions. For example, the centuries 1900 or 1800 are considered to be a leap year but they are not. Because they are divisible by 4  and also by 100.

A solution could be:
{
            if (year % 400 == 0) return true;
            if (year % 4 == 0)
            {
                if (year % 100 == 0) return false;
                else return true;
            }
            return false;
}
Maybe not that elegant but it works.

**Comment by SoftwareDojo** [comment]
You are right, I added some new test cases for the years 1600, 1800, 1900 and 2400.

`if (year % 400 == 0) return true;`
`return year % 4 == 0 && year % 100 != 0;`
Same solution but a little bit shorter :)

The solution from [wikipedia](https://en.wikipedia.org/wiki/Leap_year) is also okay.
